
import React from 'react';
import Head from 'next/head';


export default function Beslider() {
  return (
    <>
    <Head>
        
        <meta name="description" content="Generated by create next app" />
        
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

      </Head>
  
      <div className="container">
  <div className="box">
    <img src="/assets/be-slider/img1.png"/> 
    
  </div>
  <div className="box">
    <img src="/assets/be-slider/img2.png"/>
    
  </div>
  <div className="box">
    <img src="/assets/be-slider/img3.png"/>
    
  </div>
  <div className="box">
    <img src="/assets/be-slider/img4.png"/>
    
  </div>
</div>
    </>
  )
}
